weather_dict = {
    "Clear": "Ясно",
    "Sunny": "Ясно",
    "Partly cloudy": "Облачно",
    "Cloudy": "Облачно",
    "Overcast": "Облачно",
    "Mist": "Туман",
    "Fog": "Туман",
    "Freezing fog": "Туман",
    "Patchy rain possible": "Дождь",
    "Patchy light rain": "Дождь",
    "Light rain": "Дождь",
    "Moderate rain at times": "Дождь",
    "Moderate rain": "Дождь",
    "Heavy rain at times": "Дождь",
    "Heavy rain": "Дождь",
    "Light freezing rain": "Дождь",
    "Moderate or heavy freezing rain": "Дождь",
    "Light rain shower": "Дождь",
    "Moderate or heavy rain shower": "Дождь",
    "Torrential rain shower": "Дождь",
    "Patchy light rain with thunder": "Дождь",
    "Moderate or heavy rain with thunder": "Дождь",
    "Patchy snow possible": "Снег",
    "Patchy light snow": "Снег",
    "Light snow": "Снег",
    "Patchy moderate snow": "Снег",
    "Moderate snow": "Снег",
    "Patchy heavy snow": "Снег",
    "Heavy snow": "Снег",
    "Light snow showers": "Снег",
    "Moderate or heavy snow showers": "Снег",
    "Patchy light snow with thunder": "Снег",
    "Moderate or heavy snow with thunder": "Снег",
    "Patchy sleet possible": "Ледяной дождь или град",
    "Light sleet": "Ледяной дождь или град",
    "Moderate or heavy sleet": "Ледяной дождь или град",
    "Ice pellets": "Ледяной дождь или град",
    "Light showers of ice pellets": "Ледяной дождь или град",
    "Moderate or heavy showers of ice pellets": "Ледяной дождь или град",
    "Patchy light drizzle": "Морось",
    "Light drizzle": "Морось",
    "Freezing drizzle": "Морось",
    "Heavy freezing drizzle": "Морось",
    "Thundery outbreaks possible": "Штормовые условия",
    "Blowing snow": "Штормовые условия",
    "Blizzard": "Штормовые условия",
    "Patchy freezing drizzle possible": "Штормовые условия"
}

def categorize_weather_description(description):
    return weather_dict.get(description.strip(), "Неизвестно")